server {
    # FIX: Dynamically intercept Google Cloud's port assignment
    listen ${PORT};
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/ {
        proxy_pass http://10.128.0.3:8000;
        client_max_body_size 10M;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}